name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    name: Version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semantic release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
